version: 2.1 # use CircleCI 2.1
jobs: # a collection of steps
  build: # runs not using Workflows must have a `build` job as entry point
   docker: # run the steps with Docker
      - image: circleci/node:12 # ...with this image as the primary container; this is where all `steps` will run
     steps: # a collection of executable commands
       - checkout # special step to check out source code to working directory
   
        # - run:
        #   name: update-npm
        #   command: 'sudo npm install -g npm@latest'

        - run:
            name: npm show version
            command: npm -v

        - run:
            name: Install dependencies
            command: npm install

        - run:
            name: Lint code
            command: npm lint-ci

        - run:
            name: Run tests
            command: npm test

        - run:
            name: build package
            command: npm prod-build

        - run:
            name: Inspect package contents
            command: /
                tar xvf *.tgz

        - run:
            name: Audit dependencies
            command: npm audit

        - run: # run coverage report
            name: code-coverage
            command: './node_modules/.bin/nyc report --reporter=text-lcov'

        - store_artifacts: # special step to save test results as as artifact
            # Upload test summary for display in Artifacts: https://circleci.com/docs/2.0/artifacts/ 
            path: test-results.xml
            prefix: tests

        - store_artifacts: # for display in Artifacts: https://circleci.com/docs/2.0/artifacts/ 
            path: coverage
            prefix: coverage